[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "arm-none-eabi-gdb -q -x openocd.gdb"
runner = "probe-rs run --chip STM32F407VGTx"

rustflags = [
  "-C", "link-arg=--nmagic",

  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tbern.x",

  #"-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"     # Cortex-M4F and Cortex-M7F (with FPU)
